name: widget_arrows
description: Simply draw perfect arrows between widgets
version: 0.1.0
homepage: https://github.com/Schwusch/widget_arrows

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
